on: [push]

jobs:
  kernel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install linux-headers-$(uname -r) kmod
      - run: make
      - name: Test kernel module
        run: |
        sudo insmod *.ko
        sudo rmmod *.ko
        sudo dmesg | tail
